// Import the WASM module generated by Emscripten
importScripts('/sim8085.js');

let simModule = null;
let isRunning = false;
let runInterval = null;
let sharedRam = null;
let sharedRegs = null;
let sharedInPorts = null;
let sharedOutPorts = null;
let activeBreakpoints = new Set();
let tempBreakpoint = -1;
let stepOutDepth = 0;
let throughput = { steps: 0, ms: 0, mhz: 0 };

// Initialize the WASM module
Sim8085Module().then((instance) => {
  simModule = instance;
  simModule._sim_init();
  postMessage({ type: 'READY' });
});

function broadcastState(mhz = 0) {
  if (!simModule) return;
  
  // Sync WASM memory to the SharedArrayBuffer
  if (sharedRam) {
    const ptr = simModule._malloc(65536);
    simModule._sim_get_full_memory(ptr);
    const memoryView = new Uint8Array(simModule.HEAPU8.buffer, ptr, 65536);
    sharedRam.set(memoryView);
    simModule._free(ptr);
  }

  // Sync registers to the Int32Array view of the SharedArrayBuffer
  if (sharedRegs && simModule) {
    sharedRegs[0] = simModule._wasm_reg_pc();
    sharedRegs[1] = simModule._wasm_reg_sp();
    sharedRegs[2] = simModule._wasm_reg_a();
    sharedRegs[3] = simModule._wasm_reg_b();
    sharedRegs[4] = simModule._wasm_reg_c();
    sharedRegs[5] = simModule._wasm_reg_d();
    sharedRegs[6] = simModule._wasm_reg_e();
    sharedRegs[7] = simModule._wasm_reg_h();
    sharedRegs[8] = simModule._wasm_reg_l();
    sharedRegs[9] = simModule._wasm_reg_flags();
    sharedRegs[10] = simModule._wasm_reg_halted();
    sharedRegs[11] = simModule._wasm_reg_has_error();
    sharedRegs[12] = simModule._sim_get_cycles_lo();
    sharedRegs[13] = simModule._sim_get_cycles_hi();

    // Snapshot and sync interrupt states
    simModule._wasm_snap_ints();
    sharedRegs[14] = simModule._wasm_int_iff();
    sharedRegs[15] = simModule._wasm_int_mask();
    sharedRegs[16] = simModule._wasm_int_rst75ff();
    sharedRegs[17] = simModule._wasm_int_trap_pend();
    sharedRegs[18] = simModule._wasm_int_rst65();
    sharedRegs[19] = simModule._wasm_int_rst55();
  }

  // Sync I/O Ports to SharedArrayBuffer
  if (sharedInPorts && sharedOutPorts && simModule) {
    const inPtr = simModule._wasm_get_all_input_ports();
    const inView = new Uint8Array(simModule.HEAPU8.buffer, inPtr, 256);
    sharedInPorts.set(inView);

    const outPtr = simModule._wasm_get_all_output_ports();
    const outView = new Uint8Array(simModule.HEAPU8.buffer, outPtr, 256);
    sharedOutPorts.set(outView);
  }
  
  // Dispatch a lightweight signal to trigger UI re-renders
  postMessage({ type: 'STATE_UPDATE', payload: { mhz } });
}

function runLoop() {
  if (!isRunning) return;

  const t0 = performance.now();
  let executedSteps = 0;
  
  // Run the simulation natively for up to 16ms (~60 FPS) to keep the UI smooth
  while (isRunning && (performance.now() - t0 < 16)) {
    // Execute 100,000 instructions at once entirely inside the WASM engine.
    // This eliminates the overhead of crossing the JS-WASM boundary 100,000 times.
    const steps = simModule._sim_run(100000);
    executedSteps += steps;
    
    const pc = simModule._wasm_reg_pc();
    
    // If we hit our temporary step-over breakpoint
    if (tempBreakpoint !== -1 && pc === tempBreakpoint) {
      isRunning = false;
      break;
    }

    // If it ran fewer steps than requested, it hit a breakpoint, HLT, or error
    if (steps < 100000 || simModule._wasm_reg_halted() || simModule._wasm_reg_has_error()) {
      isRunning = false;
      break;
    }
  }

  const t1 = performance.now();
  throughput.steps += executedSteps;
  throughput.ms += (t1 - t0);
  if (throughput.ms >= 250) { // Update speedometer every 250ms
    throughput.mhz = (throughput.steps / throughput.ms) / 1000;
    throughput.steps = throughput.ms = 0;
  }

  // Cleanup tempBreakpoint if execution stopped for ANY reason
  if (!isRunning && tempBreakpoint !== -1) {
    simModule._sim_clear_all_breakpoints();
    activeBreakpoints.forEach(addr => simModule._sim_set_breakpoint(addr));
    tempBreakpoint = -1;
  }

  // Sync the 64KB RAM and Registers to the UI only once per frame
  broadcastState(throughput.mhz);

  if (isRunning) {
    // Yield briefly to process incoming messages (like "PAUSE"), then continue
    setTimeout(runLoop, 0); 
  }
}

function stepOutLoop() {
  if (!isRunning) return;

  const t0 = performance.now();
  let executedSteps = 0;
  
  // Step out manually in a fast JS loop tracking exact PC branches
  while (isRunning && (performance.now() - t0 < 16)) {
    const currPc = simModule._wasm_reg_pc();
    const instr = simModule._sim_read_byte(currPc);
    
    simModule._sim_step();
    executedSteps++;
    const nextPc = simModule._wasm_reg_pc();
    
    const isCall = [0xCD, 0xDC, 0xD4, 0xCC, 0xC4, 0xF4, 0xFC, 0xEC, 0xE4].includes(instr);
    const isRst = [0xC7, 0xCF, 0xD7, 0xDF, 0xE7, 0xEF, 0xF7, 0xFF].includes(instr);
    const isRet = [0xC9, 0xD8, 0xD0, 0xC8, 0xC0, 0xF8, 0xF0, 0xE8, 0xE0].includes(instr);
    
    // Check if instruction branched (PC didn't just step over the instruction bytes)
    if ((isCall && nextPc !== currPc + 3) || (isRst && nextPc !== currPc + 1)) {
      stepOutDepth++;
    } else if (isRet && nextPc !== currPc + 1) {
      if (stepOutDepth === 0) {
        isRunning = false;
        break;
      } else {
        stepOutDepth--;
      }
    }
    
    if (simModule._wasm_reg_halted() || simModule._wasm_reg_has_error() || activeBreakpoints.has(nextPc)) {
      isRunning = false;
      break;
    }
  }
  
  const t1 = performance.now();
  throughput.steps += executedSteps;
  throughput.ms += (t1 - t0);
  if (throughput.ms >= 250) {
    throughput.mhz = (throughput.steps / throughput.ms) / 1000;
    throughput.steps = throughput.ms = 0;
  }
  
  broadcastState(throughput.mhz);
  if (isRunning) setTimeout(stepOutLoop, 0);
}

self.onmessage = function(e) {
  const { id, type, payload } = e.data;
  
  switch (type) {
    case 'INIT_SHARED_MEM':
      sharedRam = new Uint8Array(payload);
      break;

    case 'INIT_SHARED_REGS':
      sharedRegs = new Int32Array(payload);
      break;

    case 'INIT_SHARED_IO':
      sharedInPorts = new Uint8Array(payload, 0, 256);
      sharedOutPorts = new Uint8Array(payload, 256, 256);
      break;

    case 'ASSEMBLE':
      if (!simModule) {
        postMessage({ id, type: 'ERROR', payload: 'Simulator not initialized' });
        break;
      }
      
      // Allocate memory for the assembly string (max 4 bytes per UTF-16 char + null terminator)
      const maxBytes = (payload.code.length * 4) + 1;
      const ptr = simModule._malloc(maxBytes);
      simModule.stringToUTF8(payload.code, ptr, maxBytes);
      
      // Call the WASM assembler
      const ok = simModule._wasm_assemble(ptr);
      simModule._free(ptr);
      
      if (ok) {
        // Sync new memory (compiled program) and reset registers to SharedArrayBuffers
        broadcastState();
        
        // Resolve the UI's promise with success metadata
        postMessage({ id, type: 'RESULT', payload: { 
          ok: true, 
          entryPoint: simModule._wasm_asm_entry_point(),
          bytesEmitted: simModule._wasm_asm_bytes_emitted()
        }});
      } else {
        // Retrieve the error details
        const errLine = simModule._wasm_asm_error_line();
        const errMsgPtr = simModule._wasm_asm_error_msg();
        const errorMsg = simModule.UTF8ToString(errMsgPtr);
        
        // Resolve the UI's promise gracefully with the error so it can be displayed
        postMessage({ id, type: 'RESULT', payload: { ok: false, errorLine: errLine, errorMsg } });
      }
      break;
      
    case 'RUN':
      if (!isRunning) {
        throughput = { steps: 0, ms: 0, mhz: 0 };
        isRunning = true;
        runLoop();
      }
      break;
      
    case 'PAUSE':
      isRunning = false;
      throughput.mhz = 0;
      broadcastState(0);
      break;

    case 'STEP':
      if (simModule && !isRunning) {
        throughput.mhz = 0;
        simModule._sim_step();
        broadcastState(0);
      }
      break;

    case 'STEP_OVER':
      if (!simModule || isRunning) break;
      const pc = simModule._wasm_reg_pc();
      const op = simModule._sim_read_byte(pc);
      
      const isCall = [0xCD, 0xDC, 0xD4, 0xCC, 0xC4, 0xF4, 0xFC, 0xEC, 0xE4].includes(op);
      const isRst = [0xC7, 0xCF, 0xD7, 0xDF, 0xE7, 0xEF, 0xF7, 0xFF].includes(op);
      
      if (isCall || isRst) {
        tempBreakpoint = pc + (isCall ? 3 : 1);
        simModule._sim_set_breakpoint(tempBreakpoint);
        throughput = { steps: 0, ms: 0, mhz: 0 };
        isRunning = true;
        runLoop();
      } else {
        throughput.mhz = 0;
        simModule._sim_step();
        broadcastState(0);
      }
      break;

    case 'STEP_OUT':
      if (!simModule || isRunning) break;
      isRunning = true;
      stepOutDepth = 0;
      throughput = { steps: 0, ms: 0, mhz: 0 };
      stepOutLoop();
      break;

    case 'WRITE_BYTE':
      if (simModule) simModule._sim_write_byte(payload.addr, payload.val);
      if (sharedRam) sharedRam[payload.addr] = payload.val;
      break;
      
    case 'SET_BREAKPOINT':
      activeBreakpoints.add(payload.addr);
      if (simModule) simModule._sim_set_breakpoint(payload.addr);
      break;

    case 'CLEAR_BREAKPOINT':
      activeBreakpoints.delete(payload.addr);
      if (simModule) {
        simModule._sim_clear_all_breakpoints();
        activeBreakpoints.forEach(addr => simModule._sim_set_breakpoint(addr));
      }
      break;
      
    case 'CLEAR_ALL_BREAKPOINTS':
      activeBreakpoints.clear();
      if (simModule) simModule._sim_clear_all_breakpoints();
      break;

    case 'RESTORE_SNAPSHOT':
      if (!simModule) break;
      const snap = payload;
      
      const ramPtr = simModule._malloc(snap.ram.length);
      const memoryView = new Uint8Array(simModule.HEAPU8.buffer, ramPtr, snap.ram.length);
      memoryView.set(snap.ram);
      simModule._sim_restore_snapshot(0, 0, ramPtr, snap.ram.length);
      simModule._free(ramPtr);
      
      const r = snap.regs;
      simModule._wasm_restore_regs(r.a, r.b, r.c, r.d, r.e, r.h, r.l, r.flags, r.pc, r.sp);
      
      broadcastState();
      break;

    case 'ASSERT_INTERRUPT':
      if (simModule) simModule._sim_assert_interrupt(payload.intType);
      break;
      
    case 'DEASSERT_INTERRUPT':
      if (simModule) simModule._sim_deassert_interrupt(payload.intType);
      break;

    case 'SET_INPUT_PORT':
      if (simModule) simModule._sim_set_input_port(payload.port, payload.val);
      if (sharedInPorts) sharedInPorts[payload.port] = payload.val;
      break;
  }
};