export const EXAMPLES = {

  'Tests': {

    'Data Transfer': `; ── DATA TRANSFER TESTS ──────────────────────────────────────────
; Tests: MVI, MOV, MOV M, LDA/STA, LHLD/SHLD, LDAX/STAX, XCHG, LXI
; Run → should reach HLT cleanly. Any ASSERT failure stops with error.
    org     100H
    kickoff 100H

; MVI: load immediate value
    mvi a, 42H
    assert A, 42H

; MOV r,r: register to register
    mvi b, 0AAH
    mov a, b
    assert A, 0AAH
    mvi c, 55H
    mov b, c
    assert B, 55H

; MOV to/from M (memory via HL)
    lxi h, 300H
    mvi m, 7FH
    mov a, m
    assert A, 7FH
    assert MEM, 300H, 7FH

; STA / LDA: direct memory access
    mvi a, 0A5H
    sta 400H
    mvi a, 00H
    lda 400H
    assert A, 0A5H
    assert MEM, 400H, 0A5H

; SHLD / LHLD: 16-bit memory access (HL stored little-endian)
    lxi h, 1234H
    shld 500H
    lxi h, 0000H
    lhld 500H
    assert HL, 1234H
    assert MEM, 500H, 34H     ; low byte first
    assert MEM, 501H, 12H     ; high byte second

; STAX / LDAX via BC
    lxi b, 600H
    mvi a, 0CDH
    stax b
    mvi a, 00H
    ldax b
    assert A, 0CDH
    assert MEM, 600H, 0CDH

; STAX / LDAX via DE
    lxi d, 601H
    mvi a, 0EFH
    stax d
    mvi a, 00H
    ldax d
    assert A, 0EFH

; XCHG: swap DE and HL
    lxi h, 1111H
    lxi d, 2222H
    xchg
    assert HL, 2222H
    assert DE, 1111H

; LXI SP
    lxi sp, 3FFEH
    assert SP, 3FFEH

    hlt`,

    'ADD & ADC': `; ── ADD & ADC TESTS ──────────────────────────────────────────────
; Covers: ADD r, ADD M, ADI, ADC r, ACI, ADD A (self)
; Corner cases: carry out, zero result, sign bit, carry propagation
    org     100H
    kickoff 100H

; ADD r: basic addition
    mvi a, 05H
    mvi b, 03H
    add b
    assert A, 08H
    assert CY, 0
    assert Z,  0
    assert S,  0

; ADD r: result is zero
    mvi a, 00H
    mvi b, 00H
    add b
    assert A, 00H
    assert Z,  1
    assert CY, 0

; ADD r: overflow → carry out (FFH + 01H = 00H, CY=1)
    mvi a, 0FFH
    mvi b, 01H
    add b
    assert A, 00H
    assert CY, 1
    assert Z,  1

; ADD r: result is negative (bit 7 set) → S=1
    mvi a, 7FH
    mvi b, 01H
    add b
    assert A, 80H
    assert S,  1
    assert CY, 0

; ADI: add immediate (wraps with carry)
    mvi a, 0FAH
    adi 0AH
    assert A, 04H
    assert CY, 1

; ADD A: double accumulator (A = A + A)
    mvi a, 40H
    add a
    assert A, 80H
    assert S,  1
    assert CY, 0

; ADD M: add memory byte via HL
    lxi h, 300H
    mvi m, 22H
    mvi a, 11H
    add m
    assert A, 33H
    assert CY, 0

; ADC r: add with carry (CY acts as extra +1)
    stc              ; CY = 1
    mvi a, 10H
    mvi b, 20H
    adc b            ; A = 10 + 20 + 1 = 31H
    assert A, 31H
    assert CY, 0

; ACI: add immediate with carry
    stc              ; CY = 1
    mvi a, 0FFH
    aci 00H          ; FFH + 00H + 1 = 00H, CY=1
    assert A, 00H
    assert CY, 1
    assert Z,  1

; ADC A with carry: A = A + A + CY
    stc              ; CY = 1
    mvi a, 40H
    adc a            ; 40 + 40 + 1 = 81H
    assert A, 81H
    assert S,  1
    assert CY, 0

; ADC: Half-carry generated by the incoming carry
    stc              ; CY = 1
    mvi a, 0FH
    aci 00H          ; A = 0F + 0 + 1 = 10H
    assert A, 10H
    assert AC, 1     ; F + 0 + 1 = 10 (carry out of bit 3)
    assert CY, 0

; SBB: Half-borrow generated by the incoming carry
    stc              ; CY = 1
    mvi a, 10H
    sbi 00H          ; A = 10 - 0 - 1 = 0FH
    assert A, 0FH
    assert AC, 1     ; 0 - 0 - 1 = -1 (borrow into bit 3)
    assert CY, 0

    hlt`,

    'SUB & SBB': `; ── SUB & SBB TESTS ──────────────────────────────────────────────
; Covers: SUB r, SUB A, SUI, SBB r, SBI
; Corner cases: borrow (CY=1), zero result, sign, SBB propagation
    org     100H
    kickoff 100H

; SUB r: basic subtraction
    mvi a, 0AH
    mvi b, 03H
    sub b
    assert A, 07H
    assert CY, 0
    assert Z,  0
    assert S,  0

; SUB r: result is zero
    mvi a, 05H
    mvi b, 05H
    sub b
    assert A, 00H
    assert Z,  1
    assert CY, 0

; SUB r: borrow (underflow) → CY=1, S=1
    mvi a, 02H
    mvi b, 05H
    sub b
    assert A, 0FDH
    assert CY, 1
    assert S,  1
    assert Z,  0

; SUB A: A - A = 0  (CY and S always clear, Z always set)
    mvi a, 55H
    sub a
    assert A, 00H
    assert Z,  1
    assert CY, 0
    assert S,  0

; SUI: subtract immediate, no borrow
    mvi a, 50H
    sui 10H
    assert A, 40H
    assert CY, 0

; SUI: subtract immediate with borrow
    mvi a, 10H
    sui 20H
    assert A, 0F0H
    assert CY, 1
    assert S,  1

; SBB r: subtract with borrow-in (CY=1 → result is one less)
    stc              ; set borrow in
    mvi a, 10H
    mvi b, 05H
    sbb b            ; A = 10H - 05H - 1 = 0AH
    assert A, 0AH
    assert CY, 0

; SBB r: borrow propagation (00H - 00H - 1 = FFH, CY=1)
    stc
    mvi a, 00H
    mvi b, 00H
    sbb b
    assert A, 0FFH
    assert CY, 1
    assert S,  1

; SBI: subtract immediate with borrow
    stc
    mvi a, 20H
    sbi 10H          ; 20H - 10H - 1 = 0FH
    assert A, 0FH
    assert CY, 0

    hlt`,

    'INC & DEC': `; ── INR / DCR / INX / DCX TESTS ──────────────────────────────────
; KEY RULE: INR/DCR do NOT affect CY.  INX/DCX affect NO flags at all.
    org     100H
    kickoff 100H

; INR r: basic increment
    mvi b, 05H
    inr b
    assert B, 06H
    assert Z,  0
    assert S,  0

; INR r: FFH → 00H  (Z=1, but CY NOT set — INR never touches CY)
    stc              ; pre-set CY=1 to prove INR preserves it
    mvi a, 0FFH
    inr a
    assert A, 00H
    assert Z,  1
    assert CY, 1     ; CY unchanged from before INR

; INR r: 7FH → 80H  (S=1, AC=1, Z=0, CY unchanged)
    mvi a, 7FH
    inr a
    assert A, 80H
    assert S,  1
    assert Z,  0

; DCR r: basic decrement
    mvi c, 05H
    dcr c
    assert C, 04H
    assert Z,  0

; DCR r: 01H → 00H  (Z=1)
    mvi a, 01H
    dcr a
    assert A, 00H
    assert Z,  1
    assert S,  0

; DCR r: 00H → FFH  (S=1, CY NOT set — DCR never touches CY)
    mvi a, 00H
    sub a            ; clear CY explicitly via SUB A
    dcr a
    assert A, 0FFH
    assert S,  1
    assert Z,  0
    assert CY, 0     ; CY still 0 (from SUB A), not touched by DCR

; INR M: increment memory byte
    lxi h, 300H
    mvi m, 0FEH
    inr m
    assert MEM, 300H, 0FFH
    inr m            ; FFH → 00H
    assert MEM, 300H, 00H
    assert Z,  1

; INX: 16-bit increment — wraps FFFFH → 0000H, NO flags touched
    stc              ; CY=1 before INX to prove flags unchanged
    lxi b, 0FFFFH
    inx b
    assert BC, 0000H
    assert CY, 1     ; INX must not clear CY

; DCX: 16-bit decrement — wraps 0000H → FFFFH, NO flags touched
    lxi d, 0000H
    dcx d
    assert DE, 0FFFFH

    hlt`,

    'AND / OR / XOR': `; ── ANA / ORA / XRA / CMA TESTS ──────────────────────────────────
; KEY FLAG RULES: all logical ops → CY=0 always.
; ANA also sets AC=0.  ORA/XRA set AC=0.
    org     100H
    kickoff 100H

; ANA r: bitwise AND, CY always 0
    stc              ; pre-set CY to prove AND clears it
    mvi a, 0FFH
    mvi b, 0F0H
    ana b
    assert A, 0F0H
    assert CY, 0
    assert S,  1
    assert Z,  0

; ANA r: result zero
    mvi a, 0F0H
    mvi b, 0FH
    ana b
    assert A, 00H
    assert Z,  1
    assert CY, 0

; ANI: AND immediate
    mvi a, 0ABH
    ani 0FH
    assert A, 0BH
    assert CY, 0

; ANA/ANI Half-Carry quirk: sets AC to OR of bit 3 of operands
    mvi a, 00H
    ani 08H
    assert AC, 1     ; (00H | 08H) & 08H != 0 -> AC=1

    mvi a, 08H
    ani 00H
    assert AC, 1     ; (08H | 00H) & 08H != 0 -> AC=1

    mvi a, 00H
    ani 00H
    assert AC, 0     ; (00H | 00H) & 08H == 0 -> AC=0

; ORA r: bitwise OR, CY always 0
    stc              ; prove CY gets cleared
    mvi a, 0F0H
    mvi b, 0FH
    ora b
    assert A, 0FFH
    assert CY, 0
    assert S,  1

; ORA A: self-OR (no change, just updates flags)
    mvi a, 55H
    ora a
    assert A, 55H
    assert CY, 0

; ORI: OR immediate
    mvi a, 00H
    ori 0FFH
    assert A, 0FFH
    assert Z,  0
    assert S,  1

; XRA r: bitwise XOR
    mvi a, 0FFH
    mvi b, 0FFH
    xra b
    assert A, 00H
    assert Z,  1
    assert CY, 0

; XRA A: self-XOR always gives zero — fastest way to clear A and set Z
    mvi a, 0ABH
    xra a
    assert A, 00H
    assert Z,  1
    assert CY, 0

; XRI: XOR immediate, toggle bits
    mvi a, 0F0H
    xri 0FFH
    assert A, 0FH
    assert S,  0
    assert CY, 0

; CMA: complement A (bitwise NOT) — does NOT affect flags
    stc
    mvi a, 55H
    cma
    assert A, 0AAH
    assert CY, 1     ; CMA leaves flags untouched

    hlt`,

    'Compare & Flags': `; ── CMP / CPI / STC / CMC / CMA TESTS ────────────────────────────
; CMP subtracts but discards result. CY=1 means A < operand (borrow).
    org     100H
    kickoff 100H

; CMP r: equal  (Z=1, CY=0)
    mvi a, 42H
    mvi b, 42H
    cmp b
    assert Z,  1
    assert CY, 0
    assert A, 42H    ; CMP must NOT change A

; CMP r: A > B  (Z=0, CY=0, no borrow)
    mvi a, 50H
    mvi b, 30H
    cmp b
    assert Z,  0
    assert CY, 0

; CMP r: A < B  (Z=0, CY=1, borrow occurred)
    mvi a, 10H
    mvi b, 20H
    cmp b
    assert Z,  0
    assert CY, 1

; CMP A: self-compare always equal (Z=1, CY=0, A unchanged)
    mvi a, 0ABH
    cmp a
    assert Z,  1
    assert CY, 0
    assert A, 0ABH

; CPI: compare with immediate
    mvi a, 80H
    cpi 80H
    assert Z,  1
    assert CY, 0

    mvi a, 7FH
    cpi 80H          ; 7FH < 80H unsigned → CY=1
    assert Z,  0
    assert CY, 1

    mvi a, 90H
    cpi 80H          ; 90H > 80H unsigned → CY=0
    assert Z,  0
    assert CY, 0

; STC: set carry unconditionally
    xra a            ; clear flags
    stc
    assert CY, 1

; CMC: complement carry
    stc
    cmc
    assert CY, 0
    cmc
    assert CY, 1

    hlt`,

    'Rotate': `; ── ROTATE INSTRUCTION TESTS ──────────────────────────────────────
; RLC/RRC: circular (bit wraps around, also goes into CY)
; RAL/RAR: rotate through CY (9-bit rotation)
    org     100H
    kickoff 100H

; RLC: bit 7 → CY and bit 0
    mvi a, 80H       ; 10000000
    rlc              ; → 00000001, CY=1
    assert A, 01H
    assert CY, 1

    mvi a, 55H       ; 01010101
    rlc              ; → 10101010, CY=0
    assert A, 0AAH
    assert CY, 0

; RLC four times: should rotate 80H back to 80H
    mvi a, 80H
    rlc
    rlc
    rlc
    rlc
    rlc
    rlc
    rlc
    rlc              ; 8 times = full rotation back
    assert A, 80H

; RRC: bit 0 → CY and bit 7
    mvi a, 01H       ; 00000001
    rrc              ; → 10000000, CY=1
    assert A, 80H
    assert CY, 1

    mvi a, 0AAH      ; 10101010
    rrc              ; → 01010101, CY=0
    assert A, 55H
    assert CY, 0

; RAL: rotate left through CY (9-bit ring)
    mvi a, 80H       ; b7=1
    stc              ; CY=1 going in
    ral              ; A = 00000001 | cy=1 = 01H, new CY = old b7 = 1
    assert A, 01H
    assert CY, 1

    mvi a, 55H       ; 01010101, CY=1 from above
    ral              ; A = 10101010 | 1 = ABH, new CY = old b7(01010101)=0
    assert A, 0ABH
    assert CY, 0

; RAR: rotate right through CY (9-bit ring)
    mvi a, 01H       ; b0=1
    stc              ; CY=1 going in
    rar              ; A = 10000000 = 80H, new CY = old b0 = 1
    assert A, 80H
    assert CY, 1

    mvi a, 0AAH      ; 10101010, CY=1 from above
    rar              ; A = 11010101 = D5H, new CY = old b0(0AAH)=0
    assert A, 0D5H
    assert CY, 0

    hlt`,

    'Jumps': `; ── CONDITIONAL JUMP TESTS ────────────────────────────────────────
; Each test uses ORA A or ADI to set flags, then checks the branch.
; If a jump fails to take (or takes when it should not), HLT is hit early.
    org     100H
    kickoff 100H

; JNZ: jump if Z=0
    mvi a, 01H
    ora a            ; Z=0 (nonzero result)
    jnz t2
    hlt              ; must not reach
t2: assert A, 01H

; JZ: jump if Z=1
    mvi a, 00H
    ora a            ; Z=1
    jz t3
    hlt
t3: assert Z, 1

; JNC: jump if CY=0
    mvi a, 0FFH
    adi 00H          ; FF+00 = FF, no carry
    jnc t4
    hlt
t4: assert CY, 0

; JC: jump if CY=1
    mvi a, 0FFH
    adi 01H          ; FF+01 overflows → CY=1
    jc t5
    hlt
t5: assert CY, 1

; JP: jump if S=0 (positive / non-negative result)
    mvi a, 7FH
    ora a            ; S=0
    jp t6
    hlt
t6: assert S, 0

; JM: jump if S=1 (minus / bit 7 set)
    mvi a, 80H
    ora a            ; S=1
    jm t7
    hlt
t7: assert S, 1

; JPO: jump if parity odd (P=0) — 01H has one 1-bit = odd
    mvi a, 01H
    ora a
    jpo t8
    hlt
t8: assert P, 0

; JPE: jump if parity even (P=1) — 03H = 00000011 has two 1-bits = even
    mvi a, 03H
    ora a
    jpe t9
    hlt
t9: assert P, 1

; JNZ NOT taken: Z=1, JNZ should fall through
    mvi a, 00H
    ora a            ; Z=1
    jnz bad_jnz
    jmp t10
bad_jnz: hlt
t10: assert Z, 1

    hlt`,

    'CALL & RET': `; ── CALL / RET / CONDITIONAL CALL & RETURN TESTS ─────────────────
; CALL pushes PC+3, jumps to subroutine. RET pops and resumes.
    org     100H
    kickoff 100H
    lxi sp, 3FFEH

; Basic CALL / RET
    call sub_basic
    assert A, 0AAH

; CZ: conditional call when Z=1
    mvi a, 00H
    ora a            ; Z=1
    cz sub_cz
    assert A, 0BBH

; CNZ: conditional call when Z=0
    mvi a, 01H
    ora a            ; Z=0
    cnz sub_cnz
    assert A, 0CCH

; CC: conditional call when CY=1
    stc
    cc sub_cc
    assert A, 0DDH

; CNC: conditional call when CY=0 (after CMC, CY becomes 0)
    stc
    cmc              ; CY=0
    cnc sub_cnc
    assert A, 0EEH

; RNZ: return if Z=0 — should return, leaving B unchanged
    mvi b, 01H
    call sub_rnz
    assert B, 01H    ; B stays 01H because RNZ returned before INR B

; CALL 5 (Intel SDK) must not corrupt the stack
    lxi sp, 3FFEH
    lxi d, 0BEEFH
    push d           ; SP=3FFCH, contains BEEF
    mvi c, 00H       ; syscall 0 = NOP
    call 5
    pop h
    assert HL, 0BEEFH ; Stack data completely untouched

    hlt

sub_basic:
    mvi a, 0AAH
    ret

sub_cz:
    mvi a, 0BBH
    ret

sub_cnz:
    mvi a, 0CCH
    ret

sub_cc:
    mvi a, 0DDH
    ret

sub_cnc:
    mvi a, 0EEH
    ret

sub_rnz:
    mvi a, 01H
    ora a            ; Z=0
    rnz              ; taken — return here
    inr b            ; NOT reached
    ret`,

    'PUSH & POP': `; ── PUSH / POP TESTS ──────────────────────────────────────────────
; PUSH decrements SP by 2 then writes; POP reads then increments SP by 2.
; Data is stored little-endian: low byte at lower address.
    org     100H
    kickoff 100H
    lxi sp, 3FFEH

; PUSH/POP B: round-trip
    lxi b, 1234H
    push b
    lxi b, 0000H     ; clear BC
    pop b
    assert BC, 1234H

; PUSH/POP D: round-trip
    lxi d, 5678H
    push d
    lxi d, 0000H
    pop d
    assert DE, 5678H

; PUSH/POP H: round-trip
    lxi h, 9ABCH
    push h
    lxi h, 0000H
    pop h
    assert HL, 9ABCH

; SP movement: each PUSH decrements SP by 2, each POP increments
    lxi sp, 3FFEH
    assert SP, 3FFEH
    push b
    assert SP, 3FFCH
    push d
    assert SP, 3FFAH
    pop d
    assert SP, 3FFCH
    pop b
    assert SP, 3FFEH

; Stack memory layout: little-endian (low byte at lower address)
    lxi b, 0AABBH
    lxi sp, 3FFEH
    push b
    assert MEM, 3FFCH, 0BBH   ; B=BB is the low byte → [SP]
    assert MEM, 3FFDH, 0AAH   ; B=AA is the high byte → [SP+1]

; PUSH/POP PSW: saves A and flags together
    mvi a, 0F0H
    stc              ; CY=1
    push psw         ; saves A=F0H, flags (with CY=1)
    mvi a, 00H
    xra a            ; A=0, CY=0, Z=1 — overwrites flags
    pop psw          ; restore A=F0H, flags with CY=1
    assert A, 0F0H
    assert CY, 1

; DAA Half-carry generation during correction
    mvi a, 0AH       ; Lower nibble > 9
    daa              ; A = 0A + 06 = 10H
    assert A, 10H
    assert AC, 1     ; 0A + 06 = 10H (carry out of bit 3)

    hlt`,

    'RIM & SIM': `; ── RIM & SIM TESTS ──────────────────────────────────────────────
; Tests IFF and interrupt mask reflection in RIM
    org     100H
    kickoff 100H

; Default state: interrupts disabled, no masks
    di
    rim
    assert A, 00H    ; IFF=0, Masks=0

; Enable interrupts
    ei
    nop              ; 1 instruction delay for EI
    rim
    assert A, 08H    ; IFF=1 (bit 3)

; Set interrupt masks
    mvi a, 0BH       ; MSE=1 (bit 3), mask RST 7.5, 6.5, 5.5 = 011
    sim
    rim
    assert A, 0BH    ; IFF=1 (08H) | Masks (03H) = 0BH

    hlt`,

    '16-bit Arithmetic': `; ── DAD / INX / DCX / SPHL TESTS ─────────────────────────────────
; DAD: 16-bit HL = HL + pair.  Only CY is affected.
; INX / DCX: 16-bit inc/dec.  NO flags are changed at all.
    org     100H
    kickoff 100H

; DAD B: HL = HL + BC, no carry
    lxi h, 1000H
    lxi b, 0200H
    dad b
    assert HL, 1200H
    assert CY, 0

; DAD B: carry out (overflow 16 bits)
    lxi h, 0FF00H
    lxi b, 0200H
    dad b
    assert HL, 0100H
    assert CY, 1

; DAD D
    lxi h, 2000H
    lxi d, 3000H
    dad d
    assert HL, 5000H
    assert CY, 0

; DAD H: HL = HL + HL (double HL)
    lxi h, 1000H
    dad h
    assert HL, 2000H
    assert CY, 0

; DAD SP
    lxi h, 1000H
    lxi sp, 2000H
    dad sp
    assert HL, 3000H

; INX: wraps FFFFH → 0000H, does NOT affect CY
    stc              ; CY=1 before INX
    lxi b, 0FFFFH
    inx b
    assert BC, 0000H
    assert CY, 1     ; CY must be unchanged by INX

; INX: regular increment
    lxi d, 1234H
    inx d
    assert DE, 1235H

; DCX: wraps 0000H → FFFFH
    lxi h, 0000H
    dcx h
    assert HL, 0FFFFH

; DCX: regular decrement
    lxi b, 0500H
    dcx b
    assert BC, 04FFH

; SPHL: SP = HL
    lxi h, 2000H
    sphl
    assert SP, 2000H

    hlt`,

    'DAA (BCD)': `; ── DAA — DECIMAL ADJUST ACCUMULATOR TESTS ───────────────────────
; After binary addition, DAA corrects A to a valid packed-BCD byte.
; Two decimal digits per byte: upper nibble = tens, lower = units.
    org     100H
    kickoff 100H

; 09 + 01 = BCD 10 (adjust lower nibble: 0AH → 10H)
    mvi a, 09H
    adi 01H          ; A = 0AH (invalid BCD)
    daa              ; → 10H  (BCD 10)
    assert A, 10H
    assert CY, 0

; 09 + 09 = BCD 18
    mvi a, 09H
    adi 09H          ; A = 12H, AC=1 (9+9=18, lower nibble carries)
    daa              ; → 18H  (BCD 18)
    assert A, 18H
    assert CY, 0

; 08 + 08 = BCD 16 (AC set because 8+8=16, lower nibble carry)
    mvi a, 08H
    adi 08H          ; A = 10H, AC=1
    daa              ; → 16H  (BCD 16)
    assert A, 16H
    assert CY, 0

; 47 + 35 = BCD 82
    mvi a, 47H
    adi 35H          ; A = 7CH
    daa              ; → 82H  (BCD 82)
    assert A, 82H
    assert CY, 0

; 99 + 01 = BCD 00 with carry (BCD overflow: 99+1=100)
    mvi a, 99H
    adi 01H          ; A = 9AH, no binary carry
    daa              ; → 00H, CY=1  (BCD 100)
    assert A, 00H
    assert CY, 1

; 99 + 99 = BCD 98 with carry (199 in BCD)
    mvi a, 99H
    adi 99H          ; A = 32H, binary CY=1
    daa              ; → 98H, CY=1
    assert A, 98H
    assert CY, 1

; 50 + 50 = BCD 00 with carry (100 in BCD)
    mvi a, 50H
    adi 50H          ; A = A0H
    daa              ; → 00H, CY=1
    assert A, 00H
    assert CY, 1

    hlt`,

  },

  'Basic': {
    'Counter': `; Increment A and B registers in a tight loop.
; Watch the Registers panel update live.
    org 100H
    kickoff 100H
    mvi a, 00H
    mvi b, 00H
loop:
    inr a
    inr b
    jnz loop
    hlt`,
  },

  'Arithmetic': {
    'Add': `; 8-bit addition: mem[val1] + mem[val2] → mem[result]
; If the sum overflows 8 bits, CY flag is set.
    org 100H
    kickoff 100H
    lda val1
    mov b, a
    lda val2
    add b               ; A = sum,  CY set on overflow
    sta result
    mvi a, 00H
    adc a               ; A = carry (0 or 1)
    sta carry_res
    hlt

; --- Data Section ---
    org 200H
val1:
    db 3CH              ; 60
val2:
    db 2AH              ; 42  (sum = 102 = 66H)
result:
    ds 1
carry_res:
    ds 1`,

    'Subtract': `; 8-bit subtraction: mem[minuend] - mem[subtrahend] → mem[result]
; CY=1 after SUB means borrow (result negative).
    org 100H
    kickoff 100H
    lda subtrahend
    mov b, a            ; B = subtrahend
    lda minuend
    sub b               ; A = minuend - subtrahend
    sta result
    hlt

; --- Data Section ---
    org 200H
minuend:
    db 5AH              ; 90
subtrahend:
    db 1EH              ; 30  (result = 60 = 3CH)
result:
    ds 1`,

    'Multiply': `; 8-bit multiply via repeated addition
; mem[multiplicand] x mem[multiplier] → mem[result] (16-bit)
    org 100H
    kickoff 100H
    lda multiplicand
    mov b, a            ; B = multiplicand
    lda multiplier
    mov c, a            ; C = multiplier (loop count)
    lxi h, 0000H        ; HL = running product
    mov a, c
    ora a
    jz done             ; multiplier = 0 → result = 0
mul:
    mov a, l
    add b
    mov l, a
    mov a, h
    aci 00H             ; propagate carry into high byte
    mov h, a
    dcr c
    jnz mul
done:
    shld result         ; store 16-bit result (lo, then hi)
    hlt

; --- Data Section ---
    org 200H
multiplicand:
    db 0CH              ; 12
multiplier:
    db 0AH              ; 10  (product = 120 = 78H)
result:
    ds 2                ; 16-bit result`,

    'Divide': `; 8-bit divide: mem[dividend] / mem[divisor]
; Quotient → mem[quotient],  Remainder → mem[remainder]
    org 100H
    kickoff 100H
    lda divisor
    mov c, a            ; C = divisor
    lda dividend
    mov b, a            ; B = working dividend
    mvi d, 00H          ; D = quotient
div:
    mov a, b
    sub c               ; A = B - divisor
    jc  done            ; borrow → B < divisor → done
    mov b, a            ; B = new remainder
    inr d               ; quotient++
    jmp div
done:
    mov a, d
    sta quotient        ; quotient
    mov a, b
    sta remainder       ; remainder
    hlt

; --- Data Section ---
    org 200H
dividend:
    db 64H              ; 100
divisor:
    db 07H              ; 7  (quotient=14, remainder=2)
quotient:
    ds 1
remainder:
    ds 1`,

    '16-bit Add': `; Add two 16-bit values using DAD (HL = HL + DE).
; Operand 1 at 'op1', operand 2 at 'op2'.
; 16-bit result stored at 'result'. CY = carry out.
    org 100H
    kickoff 100H
    lhld op1            ; HL = first operand
    xchg                ; DE = first operand
    lhld op2            ; HL = second operand
    dad d               ; HL = HL + DE
    shld result         ; store result
    hlt

; --- Data Section ---
    org 200H
op1:
    dw 12A4H            ; first operand = 12A4H (4772)
op2:
    dw 0E73H            ; second operand = 0E73H (3699)
result:
    ds 2                ; (sum = 2117H = 8471)`,

    'BCD Add': `; BCD (packed) addition using DAA.
; Two BCD digits in A and B are added and adjusted.
; Result in A is a valid two-digit BCD number.
    org 100H
    kickoff 100H
    mvi a, 47H          ; BCD 47 (= decimal 47)
    mvi b, 35H          ; BCD 35 (= decimal 35)
    add b               ; binary sum = 7CH (wrong for BCD)
    daa                 ; adjust → A = 82H (BCD 82 = decimal 82)
    sta result
    hlt

; --- Data Section ---
    org 200H
result:
    ds 1`,

    'BCD Counter': `; Count from BCD 00 to BCD 99 using DAA.
; Each pass: binary +1 then DAA corrects to valid packed BCD.
; Watch 'counter' (200H) in the Memory panel to see the value tick.
; CY=1 from DAA means the count wrapped past 99 → done.
    org 100H
    kickoff 100H
    mvi a, 00H
loop:
    sta counter         ; store current BCD value
    adi 01H             ; binary +1
    daa                 ; adjust to packed BCD (tens in upper nibble)
    jnc loop            ; CY=0: still 00..99 → continue
    hlt                 ; CY=1: overflowed past 99 → done

; --- Data Section ---
    org 200H
counter:
    ds 1`,

    '32-bit Add': `; Add two 32-bit little-endian numbers using ADC carry chain.
; A at 'val_a', B at 'val_b', sum at 'result'.
; Values chosen so carry ripples through all three low bytes:
;   A = 00FFFFFFh  +  B = 00000001h  =  01000000h
    org 100H
    kickoff 100H
    lxi h, val_a
    lxi d, val_b
    lxi b, result

    ; byte 0: plain ADD (no carry-in)
    ldax d
    add m
    stax b

    ; byte 1: ADC carries forward
    inx h
    inx d
    inx b
    ldax d
    adc m
    stax b

    ; byte 2
    inx h
    inx d
    inx b
    ldax d
    adc m
    stax b

    ; byte 3
    inx h
    inx d
    inx b
    ldax d
    adc m
    stax b

    ; carry out into byte 4
    inx b
    mvi a, 00H
    adc a
    stax b
    hlt

; --- Data Section ---
    org 200H
val_a:
    db 0FFH, 0FFH, 0FFH, 00H  ; A = 00FFFFFFh
val_b:
    db 01H, 00H, 00H, 00H     ; B = 00000001h
result:
    ds 5                      ; 32-bit sum + 1 byte for final carry`,
  },

  'Logic': {
    'AND / OR / XOR': `; Demonstrate bitwise AND, OR, and XOR.
; Operands: F0H (11110000) and AAH (10101010)
; AND → A0H   OR → FAH   XOR → 5AH
    org 100H
    kickoff 100H
    lda val1
    mov b, a
    lda val2
    ana b               ; AND: F0 & AA = A0H
    sta res_and
    lda val1
    mov b, a
    lda val2
    ora b               ; OR:  F0 | AA = FAH
    sta res_or
    lda val1
    mov b, a
    lda val2
    xra b               ; XOR: F0 ^ AA = 5AH
    sta res_xor
    hlt

; --- Data Section ---
    org 200H
val1:
    db 0F0H
val2:
    db 0AAH
res_and:
    ds 1
res_or:
    ds 1
res_xor:
    ds 1`,

    'Bit Test': `; Test whether bit 3 of 'value' is set.
; Result at 'result': 01H = bit set,  00H = bit clear.
    org 100H
    kickoff 100H
    lda value
    ani 08H             ; mask bit 3  (08H = 0000 1000)
    jz  clear
    mvi a, 01H          ; bit was set
    sta result
    hlt
clear:
    mvi a, 00H          ; bit was clear
    sta result
    hlt

; --- Data Section ---
    org 200H
value:
    db 2CH              ; 0010 1100 — bit 3 is 1
result:
    ds 1`,

    'Complement & Rotate': `; Show CMA (bitwise NOT) and RLC/RRC rotations.
    org 100H
    kickoff 100H
    mvi a, 0F0H         ; A = 1111 0000
    cma                 ; A = ~A = 0000 1111 = 0FH
    sta res_cma
    mvi a, 01H          ; A = 0000 0001
    rlc                 ; A = 0000 0010  CY=0
    rlc                 ; A = 0000 0100
    rlc                 ; A = 0000 1000
    rlc                 ; A = 0001 0000 = 10H
    sta res_rlc
    mvi a, 80H          ; A = 1000 0000
    rrc                 ; A = 0100 0000  CY=0
    rrc                 ; A = 0010 0000
    rrc                 ; A = 0001 0000 = 10H
    sta res_rrc
    hlt

; --- Data Section ---
    org 200H
res_cma: ds 1
res_rlc: ds 1
res_rrc: ds 1`,
  },

  'Memory': {
    'Block Move': `; Copy 8 bytes from 'source' to 'dest'.
    org 100H
    kickoff 100H
    lxi h, source       ; HL = source
    lxi d, dest         ; DE = destination
    mvi c, 08H          ; C  = byte count
copy:
    mov a, m            ; A = mem[HL]
    stax d              ; mem[DE] = A
    inx h
    inx d
    dcr c
    jnz copy
    hlt

; --- Data Section ---
    org 200H
source:
    db 11H, 22H, 33H, 44H, 55H, 66H, 77H, 88H
dest:
    ds 8`,

    'Memory Fill': `; Fill 16 bytes starting at 'buffer' with the value AAH.
    org 100H
    kickoff 100H
    lxi h, buffer       ; start address
    mvi b, 10H          ; count = 16
    mvi a, 0AAH         ; fill value
fill:
    mov m, a
    inx h
    dcr b
    jnz fill
    hlt

; --- Data Section ---
    org 200H
buffer:
    ds 16               ; Reserve 16 bytes for the buffer`,

    'Find Maximum': `; Find the largest byte in an 8-element array at 'array_data'.
; Result stored at 'result'.
    org 100H
    kickoff 100H
    lxi h, array_data
    mvi b, 08H          ; element count
    mvi a, 00H          ; current max
scan:
    cmp m               ; A vs mem[HL]
    jnc skip            ; if A >= mem[HL], keep A
    mov a, m            ; new maximum found
skip:
    inx h
    dcr b
    jnz scan
    sta result          ; store result (EFH = 239)
    hlt

; --- Data Section ---
    org 200H
array_data:
    db 34H, 78H, 12H, 9AH, 56H, 0BH, 0EFH, 23H
result:
    ds 1`,

    'Find Minimum': `; Find the smallest byte in an 8-element array at 'array_data'.
; Result stored at 'result'.
    org 100H
    kickoff 100H
    lxi h, array_data
    mvi b, 08H
    mov a, m            ; seed with first element
    inx h
    dcr b
scan:
    cmp m               ; A vs mem[HL]
    jc  skip            ; if A < mem[HL], A is still smaller
    mov a, m            ; new minimum found
skip:
    inx h
    dcr b
    jnz scan
    sta result          ; store result (0BH = 11)
    hlt

; --- Data Section ---
    org 200H
array_data:
    db 34H, 78H, 12H, 9AH, 56H, 0BH, 0EFH, 23H
result:
    ds 1`,
  },

  'Sorting': {
    'Bubble Sort': `; Bubble sort — sorts 10 values at 'array_data' into ascending order.
    org 100H
    kickoff 100H
    mvi  b, 09H
outer:
    lxi  h, array_data
    mov  c, b
inner:
    mov  a, m
    inx  h
    cmp  m
    jc   next
    mov  d, m           ; swap mem[HL-1] and mem[HL]
    mov  m, a
    dcx  h
    mov  m, d
    inx  h
next:
    dcr  c
    jnz  inner
    dcr  b
    jnz  outer
    hlt

; --- Data Section ---
    org 251H
array_data:
    db 34H, 30H, 26H, 23H, 20H, 17H, 14H, 10H, 07H, 03H`,

    'Selection Sort': `; Selection sort — finds the minimum and places it at the front.
; Sorts 8 bytes at 'array_data' into ascending order.
    org 100H
    kickoff 100H
    mvi  e, 08H         ; total elements
    lxi  h, array_data  ; outer pointer (i)
outer:
    dcr  e
    jz   done
    mov  d, e           ; inner count
    push h              ; save i
    mov  b, h           ; min pointer = i (hi)
    mov  c, l           ; min pointer = i (lo)
    mov  a, m           ; current min value
    inx  h
inner:
    cmp  m
    jc   no_swap
    mov  a, m           ; new min value
    mov  b, h
    mov  c, l           ; save address of new min
no_swap:
    inx  h
    dcr  d
    jnz  inner
    ; swap mem[i] and mem[min_addr]
    pop  h              ; HL = i
    push h
    mov  d, a           ; D = min value
    mov  a, m           ; A = mem[i]
    push b
    pop  h              ; HL = min address
    mov  m, a           ; mem[min] = old mem[i]
    pop  h              ; HL = i again
    mov  m, d           ; mem[i] = min value
    inx  h
    jmp  outer
done:
    hlt

; --- Data Section ---
    org 200H
array_data:
    db 45H, 12H, 78H, 03H, 9AH, 56H, 23H, 67H`,
  },

  'Algorithms': {
    'Fibonacci': `; Fibonacci sequence — stores 16 values starting at 'fib_seq'.
; F(0)=0, F(1)=1, F(2)=1, F(3)=2 … F(15)=62H (wraps at 256)
    org 100H
    kickoff 100H
    lxi  h, fib_seq
    mvi  a, 00H
    mov  m, a           ; F(0) = 0
    inx  h
    mvi  a, 01H
    mov  m, a           ; F(1) = 1
    mvi  b, 0EH         ; compute 14 more terms (F(2)..F(15))
fib:
    dcx  h
    mov  a, m           ; A = F(n-1)
    inx  h
    add  m              ; A = F(n-1) + F(n) = F(n+1)
    inx  h
    mov  m, a
    dcr  b
    jnz  fib
    hlt

; --- Data Section ---
    org 200H
fib_seq:
    ds 16               ; Reserve 16 bytes for the sequence`,

    'Factorial': `; Compute N! using repeated multiplication (repeated addition).
; N stored at 'n_val' (200H). Result at 'result' (201H). Valid for N <= 5.
    org 100H
    kickoff 100H
    lda n_val
    mov b, a            ; B = current factor (counts down N..1)
    mvi a, 01H          ; A = running result = 1
loop:
    mov c, a            ; C = current result
    mov d, b            ; D = factor (multiply count)
    mvi a, 00H
mul:
    add c               ; A += C  (repeated D times = C * B)
    dcr d
    jnz mul
    dcr b               ; next factor
    jnz loop
    sta result          ; store result
    hlt

; --- Data Section ---
    org 200H
n_val:
    db 05H              ; N = 5  →  5! = 120 = 78H
result:
    ds 1                ; Reserve 1 byte for result`,

    'GCD': `; Greatest common divisor — Euclid's subtraction algorithm.
; GCD(val1, val2) stored at 'result'.
    org 100H
    kickoff 100H
    lda val1
    mov b, a            ; B = first value
    lda val2
    mov c, a            ; C = second value
gcd:
    mov a, b
    cmp c
    jz  done            ; B == C → answer found
    jc  b_lt            ; B < C  → subtract other way
    sub c
    mov b, a            ; B = B - C
    jmp gcd
b_lt:
    mov a, c
    sub b
    mov c, a            ; C = C - B
    jmp gcd
done:
    mov a, b
    sta result
    hlt

; --- Data Section ---
    org 200H
val1:
    db 30H              ; 48
val2:
    db 14H              ; 20   GCD = 4
result:
    ds 1                ; Reserve 1 byte for the result`,

    'Delay Loop': `; Software delay using a nested counter loop.
; Inner body: DCX D (6) + MOV A,D (4) + ORA E (4) + JNZ (10) = 24 T-states.
; Total ≈ outer × inner × 24 T-states.  At 3 MHz: 10×100×24 ≈ 80 μs.
; Tune B (outer) and DE (inner) for longer or shorter delays.
; Writes FFH to 'flag_done' when complete.
    org 100H
    kickoff 100H
    mvi b, 0AH          ; outer loop count = 10
outer:
    lxi d, 0064H        ; inner loop count = 100
inner:
    dcx d               ; DE-- (6 T-states; does NOT affect flags)
    mov a, d
    ora e               ; Z=1 only when D and E are both 0
    jnz inner
    dcr b
    jnz outer
    mvi a, 0FFH
    sta flag_done       ; signal completion
    hlt

; --- Data Section ---
    org 200H
flag_done:
    ds 1                ; Reserve 1 byte for completion flag`,

    'Checksum': `; XOR checksum of a 5-byte block at 'data_block'. Result at 'checksum'.
    org 100H
    kickoff 100H
    lxi h, data_block
    mvi b, 05H
    mvi a, 00H
xloop:
    xra m               ; A ^= mem[HL]
    inx h
    dcr b
    jnz xloop
    sta checksum        ; checksum = 0AH^1BH^2CH^3DH^4EH = 10H
    hlt

; --- Data Section ---
    org 200H
data_block:
    db 0AH, 1BH, 2CH, 3DH, 4EH
    
    org 300H
checksum:
    ds 1                ; Reserve 1 byte for the checksum`,
  },

  'Strings': {
    'Length': `; Count the length of a null-terminated ASCII string.
; String stored at 200H.  Result (byte count) stored at 210H.
; "Hello" has 5 characters → 210H = 05H.
    org 100H
    kickoff 100H
    lxi  h, 200H
    mvi  b, 00H         ; B = length counter
scan:
    mov  a, m
    ora  a              ; set flags; Z=1 if null
    jz   done
    inr  b
    inx  h
    jmp  scan
done:
    mov  a, b
    sta  210H           ; store length = 05H
    hlt

; --- Data Section ---
    org 200H
string:
    db "Hello", 00H`,

    'Uppercase': `; Convert all lowercase letters in a string to uppercase.
; Works in-place.  Non-letter bytes are left unchanged.
; ASCII 'a'..'z' = 61H..7AH → subtract 20H → 'A'..'Z' = 41H..5AH.
    org 100H
    kickoff 100H
    lxi  h, 200H
loop:
    mov  a, m
    ora  a              ; null check
    jz   done
    cpi  61H            ; below 'a'?
    jc   next           ; yes — not lowercase, skip
    cpi  7BH            ; above 'z'?
    jnc  next           ; yes — not lowercase, skip
    sui  20H            ; to uppercase
    mov  m, a
next:
    inx  h
    jmp  loop
done:
    hlt

; --- Data Section ---
    org 200H
string:
    db "Hello!", 00H`,

    'Reverse': `; Reverse a null-terminated string in-place.
; DE = left pointer,  HL = right pointer,  B = char temp,  C = swap count.
; "Hello" (5 chars) → "olleH".
    org 100H
    kickoff 100H
    lxi  d, 200H        ; DE = left pointer (fixed start)
    lxi  h, 200H        ; HL = scan to find end
    mvi  c, 00H         ; C = length counter
scan:
    mov  a, m
    ora  a              ; null check
    jz   found
    inr  c
    inx  h
    jmp  scan
found:
    ; C = length.  Length < 2 → nothing to reverse.
    mov  a, c
    cpi  02H
    jc   done
    dcx  h              ; HL = last char (was pointing at null)
    ; Swap count = floor(length / 2): clear CY then shift right
    ora  a              ; A still holds length; clears CY
    rar                 ; A = length / 2 (floor)
    mov  c, a           ; C = swap count (reuse register)
swap:
    mov  b, m           ; B = right char
    ldax d              ; A = left char
    mov  m, a           ; mem[HL] = left
    mov  a, b
    stax d              ; mem[DE] = right
    inx  d              ; left pointer advances right
    dcx  h              ; right pointer advances left
    dcr  c
    jnz  swap
done:
    hlt

; --- Data Section ---
    org 200H
string:
    db "Hello", 00H`,

    'Compare': `; Compare two strings.
; Sets 'result' (210H) to 01H if equal, 00H if not.
    org 100H
    kickoff 100H
    lxi h, str1
    lxi d, str2
    
comp_loop:
    ldax d           ; Load char from str2
    cmp m            ; Compare with char from str1
    jnz not_equal
    cpi 00H          ; Are we at the null terminator?
    jz equal         ; If both are null and equal, the strings match
    inx h
    inx d
    jmp comp_loop
    
not_equal:
    mvi a, 00H
    jmp done
    
equal:
    mvi a, 01H
    
done:
    sta 210H         ; Store the result
    hlt

; --- Data Section ---
    org 200H
str1:
    db "sim8085", 00H
str2:
    db "sim8085", 00H`,

    'Copy': `; Copy a null-terminated string to a new memory location.
    org 100H
    kickoff 100H
    lxi h, source
    lxi d, dest
    
copy_loop:
    mov a, m         ; Load character from source
    stax d           ; Store character to destination
    cpi 00H          ; Check for null terminator
    jz done          ; If null, we're done
    inx h            ; Advance source pointer
    inx d            ; Advance destination pointer
    jmp copy_loop
    
done:
    hlt

; --- Data Section ---
    org 200H
source:
    db "copy test", 00H
dest:
    ds 20            ; Reserve 20 bytes for the copy`,
  },

  'I/O': {
    'Port Echo': `; Read a byte from input port 01H, write it to output port 02H.
; Before running: set port 01H value in the I/O Ports panel.
    org 100H
    kickoff 100H
    in   01H            ; A = value preset on input port 01H
    out  02H            ; write A to output port 02H (visible in panel)
    hlt`,

    'Port Counter': `; Count from 0..FFH, sending each value to output port 01H.
; Watch port 01H increment in the I/O Ports panel.
    org 100H
    kickoff 100H
    mvi a, 00H
loop:
    out  01H            ; send counter value to port 01H
    inr  a
    jnz  loop           ; stop when A wraps to 0
    hlt`,

    'Console Hello': `; Print "Hello, 8085!" to the Console panel via OUT 01H.
; Each byte written to port 01H appears as an ASCII character.
; 0AH (\\n) starts a new line.  String stored at 120H.
    org     100H
    kickoff 100H
    lxi  h, 120H       ; HL → start of string in RAM
loop:
    mov  a, m          ; A = next character byte
    ora  a             ; zero = end of string
    jz   done
    out  01H           ; write to Console port 01H
    inx  h
    jmp  loop
done:
    hlt

; --- Data Section ---
    org 120H
message:
    db "Hello, 8085!", 0AH, 00H`,

    'Keyboard Read': `; Read characters queued in the Keyboard panel (syscall C=01H).
; Type some text in the I/O PORTS → KEYBOARD section, then Run.
; Characters are stored at 200H onwards, null-terminated.
; C=01H returns 0 when the queue is empty — that ends the loop.
    org 100H
    kickoff 100H
    lxi  sp, 3FFH       ; stack must be set up before any CALL
    lxi  h, 200H        ; destination pointer
read:
    mvi  c, 01H
    call 5              ; A = next queued key (00H if empty)
    mov  m, a           ; store in memory
    ora  a              ; null check
    jz   done
    inx  h
    jmp  read
done:
    hlt`,

    'LED Count': `; Count 00000000 → 99999999 on all 8 LED fields.
; One decimal digit (0-9) stored per byte at 300H-307H.
; Field 0 (leftmost) = ten-millions; field 7 (rightmost) = units.
; At rollover the display blinks 3 times (~3 s) then restarts.
; Run at Fast or Turbo speed to watch it count up.
    org     100H
    kickoff 100H
    lxi     sp, 200H

    ; Initialise all 8 digit bytes to 0
    xra     a
    lxi     h, 300H
    mvi     b, 08H
clr:
    mov     m, a
    inx     h
    dcr     b
    jnz     clr

show:
    ; Write each digit to its field (B = field 0..7, HL = digit byte)
    mvi     b, 00H
    lxi     h, 300H
dsp:
    mvi     c, 02H
    call    5
    inr     b
    inr     l
    mov     a, b
    cpi     08H
    jnz     dsp

    ; Ripple increment from rightmost digit (307H) leftward
    lxi     h, 307H
inc:
    mov     a, m
    inr     a           ; increment this digit
    cpi     0AH         ; reached 10?
    jz      carry
    mov     m, a        ; no carry — store and show
    jmp     show
carry:
    mvi     m, 00H      ; reset digit to 0
    dcx     h           ; move one digit left
    mov     a, h
    cpi     03H         ; still within 300H-307H? (H must stay 03H)
    jnc     inc         ; yes — propagate carry
    ; Wrapped 99999999 → 00000000: blink zeros 3 times then restart
    call    blink3
    jmp     show

; --- Write all-zero digits (300H–307H) to the display ---
showz:
    mvi     b, 00H
    lxi     h, 300H
szd:
    mvi     c, 02H
    call    5
    inr     b
    inr     l
    mov     a, b
    cpi     08H
    jnz     szd
    ret

; --- Half-blink delay (~0.5 s at Fast speed; tune 0C00H if needed) ---
hdly:
    lxi     d, 0C00H
hd: dcx     d
    mov     a, d
    ora     e
    jnz     hd
    ret

; --- Blink 00000000 three times (~3 s at Fast speed) ---
; Counter stored at 308H to avoid clobbering registers used by subroutines.
blink3:
    mvi     a, 03H
    sta     308H
blk:
    call    showz       ; show 00000000
    call    hdly
    mvi     c, 03H      ; blank all fields
    call    5
    call    hdly
    lda     308H
    dcr     a
    sta     308H
    jnz     blk
    ret

    hlt`,

    'Audio Siren': `; Plays an alternating two-tone siren via the Audio Output (Port 40H).
; NOTE: Open the View Panels 🪟 menu, ensure "Audio Output" is checked,
; and click the "OFF" button in the Audio panel to turn it "ON" before running!
    org     100H
    kickoff 100H
loop:
    mvi  a, 80H         ; Tone 1 frequency
    out  40H            ; Send to audio port
    call delay

    mvi  a, 60H         ; Tone 2 frequency
    out  40H            ; Send to audio port
    call delay

    jmp  loop

delay:
    lxi  d, 0800H       ; Tune delay for Fast speed
dloop:
    dcx  d
    mov  a, d
    ora  e
    jnz  dloop
    ret`,

    'Traffic Light': `; Traffic Light Controller — 8255 PPI (Ports 00H–03H)
; Open the 🪟 Panels menu and enable "8255 PPI" to watch the lights.
; Run at Fast or Turbo speed to see the full cycle.
;
; Port A (00H): North-South  → bit 0 = Red   bit 1 = Yellow   bit 2 = Green
; Port B (01H): East-West    → bit 0 = Red   bit 1 = Yellow   bit 2 = Green
;
; Cycle: NS-Green/EW-Red → NS-Yellow/EW-Red → NS-Red/EW-Green → NS-Red/EW-Yellow

    org 100H
    kickoff 100H
    lxi sp, 1FFH

    ; Configure 8255: Mode 0, all ports output  (control word = 80H)
    mvi a, 80H
    out 03H

main:
    ; Phase 1: NS Green, EW Red
    mvi a, 04H          ; NS Green  (bit 2)
    out 00H
    mvi a, 01H          ; EW Red    (bit 0)
    out 01H
    call green_dly

    ; Phase 2: NS Yellow, EW Red
    mvi a, 02H          ; NS Yellow (bit 1)
    out 00H
    mvi a, 01H          ; EW Red    (bit 0)
    out 01H
    call amber_dly

    ; Phase 3: NS Red, EW Green
    mvi a, 01H          ; NS Red    (bit 0)
    out 00H
    mvi a, 04H          ; EW Green  (bit 2)
    out 01H
    call green_dly

    ; Phase 4: NS Red, EW Yellow
    mvi a, 01H          ; NS Red    (bit 0)
    out 00H
    mvi a, 02H          ; EW Yellow (bit 1)
    out 01H
    call amber_dly

    jmp main

green_dly:
    lxi d, 0C00H
dg: dcx d
    mov a, d
    ora e
    jnz dg
    ret

amber_dly:
    lxi d, 0400H
da: dcx d
    mov a, d
    ora e
    jnz da
    ret`,

    '8253 Timer': `; 8253 Programmable Interval Timer Setup
; Configures Counter 0 in Mode 3 (Square Wave Generator).
; To see this in action, open the 🪟 View Panels menu and check "8253 PIT".
    org 100H
    kickoff 100H

    ; Control Word:
    ; SC=00 (Counter 0), RW=11 (Read/Write LSB then MSB)
    ; M=011 (Mode 3), BCD=0 (Binary) -> 00110110 = 36H
    mvi a, 36H
    out 13H             ; Write to Control Register

    ; Load initial count (e.g. 1000 = 03E8H)
    mvi a, 0E8H
    out 10H             ; Write LSB to Counter 0
    mvi a, 03H
    out 10H             ; Write MSB to Counter 0

    hlt`,
  },

  'Interrupts': {
    'TRAP (NMI)': `; TRAP — non-maskable interrupt (vector 0024H).
; Fires regardless of EI/DI or SIM masks.
; Click FIRE next to TRAP in the Interrupts panel.
; Port 01H: main-loop counter.  Port 02H: TRAP event count.

    org  0024H          ; TRAP vector
    push psw
    lda  300H
    inr  a
    sta  300H
    out  02H            ; bump event count → port 02H
    pop  psw
    ei                  ; re-enable maskable interrupts
    ret

    org  100H
    kickoff 100H
    lxi  sp, 1FFH
    xra  a
    sta  300H           ; zero event counter
                        ; no EI needed — TRAP ignores IFF
loop:
    inr  a
    out  01H            ; main-loop counter → port 01H
    jmp  loop`,

    'RST 7.5 (Edge)': `; RST 7.5 — edge-triggered (latched) interrupt (vector 003CH).
; Each FIRE click sets the latch; the ISR clears it on service.
; Fires exactly once per click even if the click is brief.
; Port 01H: main-loop counter.  Port 02H: interrupt event count.
; Click FIRE while running to trigger.

    org  003CH          ; RST 7.5 vector
    jmp  isr

    org  100H
    kickoff 100H
    lxi  sp, 1FFH
    xra  a
    sta  300H           ; zero event counter
    ei                  ; enable interrupts

loop:
    inr  a
    out  01H            ; main-loop counter → port 01H
    jmp  loop

isr:
    push psw
    lda  300H
    inr  a
    sta  300H
    out  02H            ; event count → port 02H
    pop  psw
    ei                  ; re-enable for the next FIRE
    ret`,

    'RST 6.5 (Level)': `; RST 6.5 — level-triggered interrupt (vector 0034H).
; While the line is held HIGH the ISR fires after every EI,
; i.e. once per interrupt-return.
; Toggle RST 6.5 ON → ISR fires continuously.
; Toggle RST 6.5 OFF → stops.
; Port 01H: main-loop counter.  Port 02H: ISR event count.

    org  0034H          ; RST 6.5 vector
    jmp  isr

    org  100H
    kickoff 100H
    lxi  sp, 1FFH
    xra  a
    sta  300H
    ei

loop:
    inr  a
    out  01H
    jmp  loop

isr:
    push psw
    lda  300H
    inr  a
    sta  300H
    out  02H            ; ISR count → port 02H
    pop  psw
    ei                  ; re-enables → fires again while line is HIGH
    ret`,

    'SIM / RIM Mask': `; SIM / RIM — programmatic interrupt masking (RST 5.5, vector 002CH).
;
; Before running: assert RST 5.5 ON in the Interrupts panel.
;
; Phase 1 (20 loops): RST 5.5 masked via SIM — ISR never fires.
;   Port 03H (RIM): b0=1 mask, b3=1 IFF, b4=1 pending → 19H
; Phase 2 (infinite): mask cleared via SIM — ISR fires every pass.
;   Port 03H (RIM): b0=0 unmasked, b3=1 IFF, b4=1 pending → 18H
; Port 02H: ISR event count (stays 0 in phase 1, increments in phase 2).

    org  002CH          ; RST 5.5 vector
    jmp  isr

    org  100H
    kickoff 100H
    lxi  sp, 1FFH
    xra  a
    sta  300H           ; zero event counter

    mvi  a, 09H         ; SIM: MSE(b3)=1 + RST5.5 mask(b0)=1
    sim
    ei                  ; IFF on, but RST 5.5 masked

    mvi  b, 14H         ; 20 phase-1 iterations
phase1:
    rim
    out  03H            ; RIM result → port 03H  (expect 19H)
    dcr  b
    jnz  phase1

    mvi  a, 08H         ; SIM: MSE=1, all mask bits cleared
    sim                 ; RST 5.5 now unmasked

phase2:
    rim
    out  03H            ; RIM result → port 03H  (expect 18H)
    jmp  phase2

isr:
    push psw
    lda  300H
    inr  a
    sta  300H
    out  02H            ; event count → port 02H
    pop  psw
    ei
    ret`,
  },
}
