export const INST_HELP = {
  // Data transfer
  MOV:  { brief:'Copy register/memory to register/memory', flags:'—', bytes:1, cycles:'4 / 7 (M)', desc:'MOV dst, src copies 8-bit content of src into dst. Either operand can be M (memory at HL).', ex:'MOV A, B      ; A ← B\nMOV M, C      ; mem[HL] ← C' },
  MVI:  { brief:'Load immediate byte into register/memory', flags:'—', bytes:2, cycles:'7 / 10 (M)', desc:'MVI dst, imm8 loads an 8-bit constant. dst can be A B C D E H L or M (memory at HL).', ex:'MVI A, 42H    ; A ← 42H\nMVI M, 00H    ; mem[HL] ← 0' },
  LDA:  { brief:'Load A from 16-bit memory address', flags:'—', bytes:3, cycles:'13', desc:'Loads the byte stored at the given 16-bit address into the accumulator.', ex:'LDA 2050H     ; A ← mem[2050H]' },
  STA:  { brief:'Store A to 16-bit memory address', flags:'—', bytes:3, cycles:'13', desc:'Stores the accumulator into the byte at the given 16-bit address.', ex:'STA 2050H     ; mem[2050H] ← A' },
  LHLD: { brief:'Load HL from memory (16-bit)', flags:'—', bytes:3, cycles:'16', desc:'Loads L from addr and H from addr+1.', ex:'LHLD 2040H    ; L←mem[2040H], H←mem[2041H]' },
  SHLD: { brief:'Store HL to memory (16-bit)', flags:'—', bytes:3, cycles:'16', desc:'Stores L at addr and H at addr+1.', ex:'SHLD 2040H    ; mem[2040H]←L, mem[2041H]←H' },
  LDAX: { brief:'Load A from address in BC or DE', flags:'—', bytes:1, cycles:'7', desc:'Loads A from the address held in BC (LDAX B) or DE (LDAX D).', ex:'LDAX D        ; A ← mem[DE]' },
  STAX: { brief:'Store A to address in BC or DE', flags:'—', bytes:1, cycles:'7', desc:'Stores A at the address held in BC (STAX B) or DE (STAX D).', ex:'STAX B        ; mem[BC] ← A' },
  XCHG: { brief:'Exchange HL and DE registers', flags:'—', bytes:1, cycles:'4', desc:'Swaps the full contents of the HL and DE register pairs.', ex:'XCHG          ; HL ↔ DE' },
  LXI:  { brief:'Load register pair with 16-bit immediate', flags:'—', bytes:3, cycles:'10', desc:'Loads a 16-bit constant into BC (B), DE (D), HL (H), or SP.', ex:'LXI H, 1000H  ; HL ← 1000H' },
  PUSH: { brief:'Push register pair onto stack', flags:'—', bytes:1, cycles:'12', desc:'SP decrements by 2; high byte pushed first, then low byte. PUSH PSW pushes A and flags.', ex:'PUSH B        ; push BC\nPUSH PSW      ; push A + flags' },
  POP:  { brief:'Pop register pair from stack', flags:'— (PSW restores flags)', bytes:1, cycles:'10', desc:'Pops 2 bytes from stack into the pair. POP PSW restores A and all flags.', ex:'POP H         ; pop into HL' },
  XTHL: { brief:'Exchange HL with top of stack', flags:'—', bytes:1, cycles:'16', desc:'Swaps H with (SP+1) and L with (SP) without changing SP.', ex:'XTHL' },
  SPHL: { brief:'Copy HL into SP', flags:'—', bytes:1, cycles:'6', desc:'Loads the stack pointer with the content of HL.', ex:'SPHL          ; SP ← HL' },
  PCHL: { brief:'Jump indirect through HL', flags:'—', bytes:1, cycles:'6', desc:'Loads the program counter with HL — an indirect/computed jump.', ex:'PCHL          ; PC ← HL' },
  // Arithmetic
  ADD:  { brief:'Add register/memory to A', flags:'S Z AC P CY', bytes:1, cycles:'4 / 7 (M)', desc:'A ← A + src. Sets all arithmetic flags.', ex:'ADD B         ; A ← A + B\nADD M         ; A ← A + mem[HL]' },
  ADC:  { brief:'Add register/memory to A with carry', flags:'S Z AC P CY', bytes:1, cycles:'4 / 7 (M)', desc:'A ← A + src + CY. Used for multi-byte addition.', ex:'ADC C         ; A ← A + C + CY' },
  ADI:  { brief:'Add immediate byte to A', flags:'S Z AC P CY', bytes:2, cycles:'7', desc:'A ← A + imm8.', ex:'ADI 05H       ; A ← A + 5' },
  ACI:  { brief:'Add immediate to A with carry', flags:'S Z AC P CY', bytes:2, cycles:'7', desc:'A ← A + imm8 + CY.', ex:'ACI 02H       ; A ← A + 2 + CY' },
  DAD:  { brief:'Add register pair to HL', flags:'CY only', bytes:1, cycles:'10', desc:'HL ← HL + rp. Only CY is affected; other flags unchanged.', ex:'DAD B         ; HL ← HL + BC\nDAD SP        ; HL ← HL + SP' },
  SUB:  { brief:'Subtract register/memory from A', flags:'S Z AC P CY', bytes:1, cycles:'4 / 7 (M)', desc:'A ← A − src. CY=1 indicates a borrow.', ex:'SUB D         ; A ← A − D' },
  SBB:  { brief:'Subtract register/memory from A with borrow', flags:'S Z AC P CY', bytes:1, cycles:'4 / 7 (M)', desc:'A ← A − src − CY. Used for multi-byte subtraction.', ex:'SBB E         ; A ← A − E − CY' },
  SUI:  { brief:'Subtract immediate from A', flags:'S Z AC P CY', bytes:2, cycles:'7', desc:'A ← A − imm8.', ex:'SUI 10H       ; A ← A − 16' },
  SBI:  { brief:'Subtract immediate from A with borrow', flags:'S Z AC P CY', bytes:2, cycles:'7', desc:'A ← A − imm8 − CY.', ex:'SBI 05H' },
  INR:  { brief:'Increment register/memory by 1', flags:'S Z AC P (not CY)', bytes:1, cycles:'4 / 10 (M)', desc:'dst ← dst + 1. Does NOT affect the carry flag.', ex:'INR A         ; A ← A + 1\nINR M         ; mem[HL] ← mem[HL] + 1' },
  DCR:  { brief:'Decrement register/memory by 1', flags:'S Z AC P (not CY)', bytes:1, cycles:'4 / 10 (M)', desc:'dst ← dst − 1. Does NOT affect the carry flag.', ex:'DCR B         ; B ← B − 1' },
  INX:  { brief:'Increment register pair by 1', flags:'—', bytes:1, cycles:'6', desc:'rp ← rp + 1. No flags are affected (including CY).', ex:'INX H         ; HL ← HL + 1' },
  DCX:  { brief:'Decrement register pair by 1', flags:'—', bytes:1, cycles:'6', desc:'rp ← rp − 1. No flags are affected.', ex:'DCX D         ; DE ← DE − 1' },
  DAA:  { brief:'Decimal adjust accumulator after BCD operation', flags:'S Z AC P CY', bytes:1, cycles:'4', desc:'Corrects A after BCD addition/subtraction so both nibbles hold valid BCD digits (0–9). Must follow ADD/ADC/SUB/SBB on BCD data.', ex:'ADD B\nDAA           ; adjust for BCD' },
  // Logic
  ANA:  { brief:'AND register/memory with A', flags:'S Z P  AC=1  CY=0', bytes:1, cycles:'4 / 7 (M)', desc:'A ← A & src. Resets CY, sets AC.', ex:'ANA B         ; A ← A & B' },
  ANI:  { brief:'AND immediate with A', flags:'S Z P  AC=1  CY=0', bytes:2, cycles:'7', desc:'A ← A & imm8. Common use: masking bits.', ex:'ANI 0FH       ; keep lower nibble' },
  ORA:  { brief:'OR register/memory with A', flags:'S Z P  AC=0  CY=0', bytes:1, cycles:'4 / 7 (M)', desc:'A ← A | src. Resets CY and AC.', ex:'ORA C         ; A ← A | C' },
  ORI:  { brief:'OR immediate with A', flags:'S Z P  AC=0  CY=0', bytes:2, cycles:'7', desc:'A ← A | imm8. Common use: setting specific bits.', ex:'ORI 80H       ; set bit 7' },
  XRA:  { brief:'XOR register/memory with A', flags:'S Z P  AC=0  CY=0', bytes:1, cycles:'4 / 7 (M)', desc:'A ← A ⊕ src. XRA A is the standard way to clear A quickly.', ex:'XRA A         ; A ← 0, clears flags' },
  XRI:  { brief:'XOR immediate with A', flags:'S Z P  AC=0  CY=0', bytes:2, cycles:'7', desc:'A ← A ⊕ imm8. Common use: toggling bits.', ex:'XRI 0FFH      ; invert all bits' },
  CMA:  { brief:'Complement accumulator (bitwise NOT)', flags:'—', bytes:1, cycles:'4', desc:'A ← ~A. Inverts every bit; no flags changed.', ex:'CMA           ; A ← ~A' },
  CMC:  { brief:'Complement carry flag', flags:'CY', bytes:1, cycles:'4', desc:'CY ← ~CY. Other flags unaffected.', ex:'CMC' },
  STC:  { brief:'Set carry flag to 1', flags:'CY=1', bytes:1, cycles:'4', desc:'Sets CY to 1. Other flags unaffected.', ex:'STC' },
  CMP:  { brief:'Compare register/memory with A (sets flags only)', flags:'S Z AC P CY', bytes:1, cycles:'4 / 7 (M)', desc:'Performs A − src and sets flags without modifying A. ZF=1 means equal; CY=1 means A < src.', ex:'CMP B         ; set flags for A vs B\nJZ equal      ; jump if equal' },
  CPI:  { brief:'Compare immediate with A (sets flags only)', flags:'S Z AC P CY', bytes:2, cycles:'7', desc:'Performs A − imm8 and sets flags without changing A.', ex:'CPI 0AH       ; compare A with 10' },
  RLC:  { brief:'Rotate A left, MSB goes to CY and bit 0', flags:'CY', bytes:1, cycles:'4', desc:'Bit 7 is copied to CY and also wraps into bit 0. Other flags unchanged.', ex:'RLC           ; A: b7→CY, b7→b0' },
  RRC:  { brief:'Rotate A right, LSB goes to CY and bit 7', flags:'CY', bytes:1, cycles:'4', desc:'Bit 0 is copied to CY and also wraps into bit 7. Other flags unchanged.', ex:'RRC           ; A: b0→CY, b0→b7' },
  RAL:  { brief:'Rotate A left through carry (9-bit)', flags:'CY', bytes:1, cycles:'4', desc:'Bit 7 → CY; old CY → bit 0. All 9 bits (A + CY) rotate together.', ex:'RAL           ; CY←b7, b0←old CY' },
  RAR:  { brief:'Rotate A right through carry (9-bit)', flags:'CY', bytes:1, cycles:'4', desc:'Bit 0 → CY; old CY → bit 7. All 9 bits (A + CY) rotate together.', ex:'RAR           ; CY←b0, b7←old CY' },
  // Branch
  JMP:  { brief:'Unconditional jump to address', flags:'—', bytes:3, cycles:'10', desc:'PC ← addr. Program continues at the specified address.', ex:'JMP 0100H' },
  JC:   { brief:'Jump if carry set (CY=1)', flags:'—', bytes:3, cycles:'10 / 7', desc:'PC ← addr only if CY=1, otherwise executes next instruction.', ex:'JC carry_err' },
  JNC:  { brief:'Jump if no carry (CY=0)', flags:'—', bytes:3, cycles:'10 / 7', desc:'PC ← addr only if CY=0.', ex:'JNC continue' },
  JZ:   { brief:'Jump if zero flag set (ZF=1)', flags:'—', bytes:3, cycles:'10 / 7', desc:'PC ← addr only if ZF=1 (last result was zero).', ex:'JZ done' },
  JNZ:  { brief:'Jump if not zero (ZF=0)', flags:'—', bytes:3, cycles:'10 / 7', desc:'PC ← addr only if ZF=0. Classic loop instruction.', ex:'DCR B\nJNZ loop' },
  JP:   { brief:'Jump if positive (SF=0)', flags:'—', bytes:3, cycles:'10 / 7', desc:'PC ← addr only if SF=0 (result was non-negative).', ex:'JP positive' },
  JM:   { brief:'Jump if minus (SF=1)', flags:'—', bytes:3, cycles:'10 / 7', desc:'PC ← addr only if SF=1 (result was negative / bit 7 set).', ex:'JM negative' },
  JPE:  { brief:'Jump if parity even (PF=1)', flags:'—', bytes:3, cycles:'10 / 7', desc:'PC ← addr only if PF=1 (even number of 1-bits in result).', ex:'JPE even' },
  JPO:  { brief:'Jump if parity odd (PF=0)', flags:'—', bytes:3, cycles:'10 / 7', desc:'PC ← addr only if PF=0.', ex:'JPO odd' },
  CALL: { brief:'Unconditional subroutine call', flags:'—', bytes:3, cycles:'18', desc:'Pushes the return address (PC+3) onto the stack, then jumps to addr.', ex:'CALL delay    ; call subroutine' },
  CC:   { brief:'Call subroutine if carry (CY=1)', flags:'—', bytes:3, cycles:'18 / 9', desc:'Conditional call — pushes return addr and jumps only if CY=1.', ex:'CC overflow' },
  CNC:  { brief:'Call subroutine if no carry (CY=0)', flags:'—', bytes:3, cycles:'18 / 9', desc:'Conditional call if CY=0.', ex:'CNC proceed' },
  CZ:   { brief:'Call subroutine if zero (ZF=1)', flags:'—', bytes:3, cycles:'18 / 9', desc:'Conditional call if ZF=1.', ex:'CZ zero_case' },
  CNZ:  { brief:'Call subroutine if not zero (ZF=0)', flags:'—', bytes:3, cycles:'18 / 9', desc:'Conditional call if ZF=0.', ex:'CNZ loop' },
  CP:   { brief:'Call subroutine if positive (SF=0)', flags:'—', bytes:3, cycles:'18 / 9', desc:'Conditional call if SF=0.', ex:'CP pos_handler' },
  CM:   { brief:'Call subroutine if minus (SF=1)', flags:'—', bytes:3, cycles:'18 / 9', desc:'Conditional call if SF=1.', ex:'CM neg_handler' },
  CPE:  { brief:'Call subroutine if parity even (PF=1)', flags:'—', bytes:3, cycles:'18 / 9', desc:'Conditional call if PF=1.', ex:'CPE even_handler' },
  CPO:  { brief:'Call subroutine if parity odd (PF=0)', flags:'—', bytes:3, cycles:'18 / 9', desc:'Conditional call if PF=0.', ex:'CPO odd_handler' },
  RET:  { brief:'Return from subroutine', flags:'—', bytes:1, cycles:'10', desc:'Pops the return address from the stack back into PC.', ex:'RET' },
  RC:   { brief:'Return if carry (CY=1)', flags:'—', bytes:1, cycles:'12 / 6', desc:'Conditional return — pops PC only if CY=1.', ex:'RC' },
  RNC:  { brief:'Return if no carry (CY=0)', flags:'—', bytes:1, cycles:'12 / 6', desc:'Conditional return if CY=0.', ex:'RNC' },
  RZ:   { brief:'Return if zero (ZF=1)', flags:'—', bytes:1, cycles:'12 / 6', desc:'Conditional return if ZF=1.', ex:'RZ' },
  RNZ:  { brief:'Return if not zero (ZF=0)', flags:'—', bytes:1, cycles:'12 / 6', desc:'Conditional return if ZF=0.', ex:'RNZ' },
  RP:   { brief:'Return if positive (SF=0)', flags:'—', bytes:1, cycles:'12 / 6', desc:'Conditional return if SF=0.', ex:'RP' },
  RM:   { brief:'Return if minus (SF=1)', flags:'—', bytes:1, cycles:'12 / 6', desc:'Conditional return if SF=1.', ex:'RM' },
  RPE:  { brief:'Return if parity even (PF=1)', flags:'—', bytes:1, cycles:'12 / 6', desc:'Conditional return if PF=1.', ex:'RPE' },
  RPO:  { brief:'Return if parity odd (PF=0)', flags:'—', bytes:1, cycles:'12 / 6', desc:'Conditional return if PF=0.', ex:'RPO' },
  RST:  { brief:'Software restart (interrupt vector call)', flags:'—', bytes:1, cycles:'12', desc:'RST n pushes PC and jumps to address n×8 (0H–38H). Used for interrupt service routines.', ex:'RST 7         ; push PC, jump to 0038H' },
  // I/O and control
  IN:   { brief:'Read byte from I/O port into A', flags:'—', bytes:2, cycles:'10', desc:'A ← port(imm8). Reads from the given 8-bit I/O port number.', ex:'IN 01H        ; A ← port 1' },
  OUT:  { brief:'Write A to I/O port', flags:'—', bytes:2, cycles:'10', desc:'port(imm8) ← A. Writes the accumulator to the given 8-bit I/O port.', ex:'OUT 01H       ; port 1 ← A' },
  HLT:  { brief:'Halt the processor', flags:'—', bytes:1, cycles:'5', desc:'Stops execution. The CPU enters a halted state until an interrupt or hardware reset occurs.', ex:'HLT' },
  NOP:  { brief:'No operation — does nothing for 4 cycles', flags:'—', bytes:1, cycles:'4', desc:'Advances PC by 1 and burns 4 clock cycles. Used for timing delays and code alignment.', ex:'NOP' },
  EI:   { brief:'Enable maskable interrupts', flags:'—', bytes:1, cycles:'4', desc:'Sets the interrupt-enable flip-flop (INTE). Interrupts are acknowledged after the next instruction completes.', ex:'EI\nRET           ; enable before return' },
  DI:   { brief:'Disable maskable interrupts', flags:'—', bytes:1, cycles:'4', desc:'Resets INTE so maskable interrupts (INTR, RST5.5, RST6.5, RST7.5) are ignored.', ex:'DI' },
  RIM:  { brief:'Read interrupt mask into A', flags:'—', bytes:1, cycles:'4', desc:'Loads A with interrupt mask bits, pending interrupt flags, and the SID (serial input data) bit.', ex:'RIM           ; read interrupt status' },
  SIM:  { brief:'Set interrupt mask from A', flags:'—', bytes:1, cycles:'4', desc:'Uses A to set RST5.5/RST6.5/RST7.5 masks and write the SOD (serial output data) bit.', ex:'SIM           ; write interrupt mask' },
  // Assembler directives
  ORG:     { brief:'Set assembly origin address', flags:'—', bytes:0, cycles:'—', desc:'Moves the assembly pointer to the given address. All instructions and data after ORG are placed starting at that address. Does not emit any machine code.', ex:'ORG 0100H\nMVI A, 42H    ; assembled at 0100H' },
  KICKOFF: { brief:'Set the program entry point (start address)', flags:'—', bytes:0, cycles:'—', desc:'Tells the simulator which address to load into PC when the program is reset or first built. Unlike ORG it does not move the assembly pointer — use it once, usually before your first ORG or at the top of the file.', ex:'KICKOFF 0200H ; PC starts at 0200H\nORG 0200H\nMVI A, 01H' },
  SETBYTE: { brief:'Write a byte into memory at assembly time', flags:'—', bytes:1, cycles:'—', desc:'Writes a single 8-bit value directly into the simulator RAM at the specified address during assembly. Useful for pre-initialising data areas before the program runs.', ex:'SETBYTE 2050H, 0FFH  ; mem[2050H] = FFH' },
  SETWORD: { brief:'Write a 16-bit word into memory at assembly time (little-endian)', flags:'—', bytes:2, cycles:'—', desc:'Writes a 16-bit value into two consecutive bytes in little-endian order: low byte at addr, high byte at addr+1. Handy for pre-loading address tables or 16-bit constants.', ex:'SETWORD 2060H, 1A2BH ; mem[2060H]=2BH, mem[2061H]=1AH' },
  ASSERT:  { brief:'Simulator assertion — halt with error if value does not match', flags:'—', bytes:'3–5', cycles:'—', desc:'Simulator-only directive (encoded as opcode DDH). At runtime, compares a register, flag, register pair, or memory byte against an expected value. If they differ, execution stops immediately and the status bar shows what was expected vs. what was found. Use in test programs to verify correctness step-by-step.\n\nForms and encoded sizes:\n  ASSERT r, val      — 8-bit register B C D E H L M A  (3 bytes)\n  ASSERT f, 0|1      — flag: CY Z S P AC               (3 bytes)\n  ASSERT rp, val16   — 16-bit pair: BC DE HL SP PC     (4 bytes)\n  ASSERT MEM, addr, val — byte at memory address       (5 bytes)\n\nNot a real 8085 instruction; opcode DDH is undefined on real hardware.', ex:'ASSERT A,   42H         ; stop if A ≠ 42H\nASSERT CY,  1           ; stop if carry ≠ 1\nASSERT HL,  1234H       ; stop if HL ≠ 1234H\nASSERT MEM, 0300H, 0FFH ; stop if mem[0300H] ≠ FFH' },
}

